### ISSUE TITLE
MetafieldValue::get(int) returns wrong value

### ISSUE THREAD

**Issue by kusmierz** [dreamcommerce/shop-appstore-lib#1]
According to the [documentation](https://developers.shoper.pl/developers/api/resources/metafield-values/get) and attached there example, following code should return an object of [Resource\MetafieldValue](https://developers.shoper.pl/developers/api/resources/metafield-values) type.

```php
$rMetafieldValue = new \DreamCommerce\Resource\MetafieldValue($client);
$result = $rMetafieldValue->get(1084);

var_dump($result);
// printf("#%d - %s\n", $result->value_id, $result->value);
```

instead, it returns `DreamCommerce\ResourceList` instance.

```
object(DreamCommerce\ResourceList)[405]
  public 'count' => int 0
  public 'page' => null
  public 'pages' => int 0
  private 'storage' (ArrayObject) => 
    object(ArrayObject)[386]
      private 'storage' => 
        array (size=0)
          empty
```

**Comment by kusmierz** [comment]
@jedi-pl could you look at this? thanks in advance!

**Comment by er1z** [comment]
Should be fixed now.

**Comment by kusmierz** [comment]
Now it returns wrong results for get and list methods (`get()` and `get(int)` respectively)... See my comment to 1712b12.

**Comment by er1z** [comment]
Try _dev_ branch and _55e7bb28c5134f6971d4d67c602e8f05dc8e81be_ commit.

If everything is ok, I'll put into main branch and release publicily.

**Comment by Kyniu** [comment]
I've tested this change. I think it is working

**Comment by deallas** [comment]
Rewrite a method isCollection is completely unnecessary. I removed it from branch _dev_. Please revalidate your requests and response with commit _ee84788b937451c27f0c515e8fd48cbf7c37695f_

```php
$rMetafield = new DreamCommerce\Resource\Metafield($client);
$metafieldId = $rMetafield->post('system', array(
    'namespace' => 'system',
    'key' => 'test2' . time(),
    'description' => 'test3',
    'type' => 1
));
echo 'Metafield ID: ' . $metafieldId . PHP_EOL;
$rMetafieldValue = new DreamCommerce\Resource\MetafieldValue($client);
$valueId = $rMetafieldValue->post(array(
    'metafield_id' => $metafieldId,
    'value' => 12345
));
echo 'Metafield value ID: ' . $valueId . PHP_EOL . PHP_EOL;

$result = $rMetafieldValue->get($valueId);
assert($result instanceof ArrayObject);
var_dump($result);

// Download all MetafieldValue objects
$list = $rMetafieldValue->get();
assert($list instanceof \DreamCommerce\ResourceList);
var_dump($list);

// Download MetafieldValue objects for Metafield ID
$listFiltered = $rMetafieldValue->filters(array('metafield_id' => $metafieldId))->get();
assert($listFiltered instanceof \DreamCommerce\ResourceList);
var_dump($listFiltered);

echo PHP_EOL . PHP_EOL;
```

**Comment by kusmierz** [comment]
@deallas please rethink about this commit again or fix the doc, because it is different then in the code.

**Comment by kusmierz** [comment]
Sorry, my fault, it's ok now.
