### ISSUE TITLE
Filter method in resources doesn't work

### ISSUE THREAD

**Issue by Lukasz-Chowaniec** [dreamcommerce/shop-appstore-lib#21]
When filternig products via "code" field:
`$resource = new Product($this->client);
        $resource->filters([
            'code' => [
                '=' => '9909000000540',
            ],
        ]);`
I got an error: 

> DreamCommerce\ShopAppstoreLib\Resource\Exception\NotFoundException
{"error":"invalid_request","error_description":"Resource not found"}

While using:
`    $resource = new Product($this->client);
        $resource->filters([
            'product_id' => [
                '=' => 15,
            ],
        ]);
        $product = $resource->get();`
everything works fine. 

Where is the problem?

**Comment by kotarb** [comment]
"code" field is part of ProductStock resource, although is also returned in Product resource.

The correct way to filter in this situation is by referencing to stock data using `stock.code` :

`$resource = new Product($this->client); $resource->filters([ 'stock.code' => [ '=' => '9909000000540', ], ]);`
