### ISSUE TITLE
After edit apllication settings metafields coulndn't be loaded

### ISSUE THREAD

**Issue by Kyniu** [dreamcommerce/shop-appstore-lib#6]
In situation when I'm changing some settings in my application appearance and I accept updates in admin panel, metafields in snippets are being remove. I have to reinstall this application to fix it. It is some kind of bug?

**Comment by deallas** [comment]
This is not a bug. We removed earlier all metafields when we fixed issue #5

**Comment by Kyniu** [comment]
I don't think so. This is step by step instruction to reproduce "the bug":

1. On freshly installed application, metafields have correct values. Also, metafield values are correctly displayed/parsed in shop's snippets.
1. On https://panel.shoper.pl I'm editing app settings (changing html/js snippets with {metafields})
1. I'm updating application in my dev-shop
1. Now I can get correct metafields values by API but snippets won't parse/display any {metafields}. I have empty values for any metafield values in snippets.

**Comment by kusmierz** [comment]
If you need any additional info about it, just contact us directly.

**Comment by deallas** [comment]
Fixed in version 5.7.6
